repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black

  # - repo: https://github.com/pre-commit/mirrors-mypy.git
  #   rev: v1.1.1
  #   hooks:
  #     - id: mypy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
      - id: ruff-format

default_stages:
  - commit
  - push
