[project]
name = "py"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "shiyang07ca", email = "shiyang07ca@gmail.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "UNLICENSED"}


[tool.pdm]
distribution = false
